### ISSUE TITLE
信息报错

### ISSUE THREAD

**Issue by wangtao2855** [songmao123/WanAndroid#2]
Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86
        is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:12:5-87:19 to override.

**Comment by sqsong66** [comment]
我不知道你这是不是环境的问题，我这儿是没问题的。看那提示， 你看一下gradle文件里面是不是引用了com.android.support:support-compat库，由于我这使用的是androidx库，所以不需要引用com.android.support:support-compat库， 可能两个同时引用了导致了冲突。

**Comment by wangtao2855** [comment]
搞定了 原因是我的as gradle是3.1.4版本的 androidx 需要gradle必须在3.2.0以上的版本. 我改过来了 然后OK了.谢谢大神 最近学kotlin,找几个demo看看大神怎么写的.

**Comment by sqsong66** [comment]
我也是学习，有什么问题可以一起交流

**Comment by wangtao2855** [comment]
anko 我认为您里面可以引入这个库哈

**Comment by sqsong66** [comment]
额！有时间可以了解一下
